export const configKeys = {
    SECOND_NATURE_USER: process.env.NEXT_PUBLIC_SECOND_NATURE_USER as string,
    SECOND_NATURE_SUBSCRIPTION: process.env.NEXT_PUBLIC_SECOND_NATURE_SUBSCRIPTION as string,
    SECOND_NATURE_API_KEY: process.env.NEXT_PUBLIC_SECOND_NATURE_API_KEY as string,
    SECOND_NATURE_CLIENT_KEY: process.env.NEXT_PUBLIC_SECOND_NATURE_CLIENT_KEY as string,
  };